### ISSUE TITLE
Resume Review: Aman Kumar

### ISSUE THREAD

**Issue by amankumarkeshu** [karngyan/karngyan#4]
- Resume Link: https://drive.google.com/file/d/1teoa-MDr0-dIltiWRCI8KZDjcYq1m58o/view
- Purpose: Full Time/6 Months Internship
- Remarks: Software Engineer

**Comment by karngyan** [comment]
Hey man,

So the resume looks pretty good. The content is great. Here are a few internal things that I'd like to suggest. You can choose whatever you feel like.

- Think about single column instead of double. It's pretty opinionated but I think it gets easier for a recruiter to may be go through the resume easily and not waste time on deciding which column to read first. As a plus point single column resumes are easily parsed by certain ATSs used by multiple companies. You can check if your resume is ATS Compliant or not on a few platforms online.

- I'm sure if you adopt a single column resume, certain sections won't fit into a single page. So may be you can choose any of the following sections to not include in the resume.
  - Class X and XII results - I think you have enough experience that these actually do not matter.
  - May be add ACM and IET into extra curricular instead of Work Experience.
  - Shorten the Awards Section.

- The projects you mentioned seem really cool. It'd be awesome if you can host the code on GitHub and add the repo links to the resume. Don't forget to add a kick-ass documentation for them.

### Technical Issues

- LinkedIn URL below your name points to your GitHub Account.
- Just like mail URLs are prefixed by a **mailto:**, you can add a link to your phone number as well, e.g. `tel:1234567891`. This is just an accessibility thing.

All the best buddy! And believe in your skills more than anything on the D-Day. 

If you have any more things to discuss, please mention them here. Else don't forget to close the issue. :1234: 

Happy Coding! 🥳

**Comment by amankumarkeshu** [comment]
Thank you so much Gyan, for the effort to review my resume and giving me some gyan. 😛

**Comment by karngyan** [comment]
Anytime man.
