### ISSUE TITLE
Resume Review: Vibhu Bhatia

### ISSUE THREAD

**Issue by vibhubhatia007** [karngyan/karngyan#5]
- Resume Link: https://drive.google.com/file/d/1eFy37touIjlCsq2w16Tu1m3b_eIuXn56/view?usp=sharing
- Purpose: Internship

**Comment by karngyan** [comment]
Hi Vibhu,

I'd like to apologize for such a long delay.

So let's get to it. These are just my opinions and you may or may not choose some or all.

- Too colorful.
- Your photo, too casual. I'd recommend not having the photo altogether.
- There are a few typos in the resume, like `ingridients`.
- GitHub Projects locations are just text, converting them to links will be helpful. As most of the placements will be online due to COVID now.
- For projects, add a few more lines about your achievements while overcoming any problems you had while developing the project.
- For positions of responsibility, please add some contributions you made to your college clubs.
- CodeChef Rating is not an achievement. Maybe you can add another section for Online Presence. World Ranks are deceiving when it's Division Specific.
- Maybe add a section on Skills/Technical Proficiency.

Apart from the above points, the resume is good. Now make sure you design your resumes according to the job you apply for.
Once you clear the online round, your interview will highly depend on how you present yourself and your technical communication rather than your resume. It'll have less impact but it is important for you to not add anything you're not aware of.

All the best buddy! And believe in your skills more than anything on the D-Day. 

If you have any more things to discuss, please mention them here. Else don't forget to close the issue. :1234: 

Happy Coding! 🥳

**Comment by vibhubhatia007** [comment]
Thank you bhaiya for such a detailed review
